### ISSUE TITLE
Dev environment setup and running unit tests

### ISSUE THREAD

**Issue by jeffmadrid** [arlyon/aiobreaker#7]
Hi there, just read your code and am pretty keen on contributing with a feature. Wanted to make a start with the unit tests but it seems to be failing on my machine. 😢 

Current setup:
> python3 -m venv venv
source venv/bin/activate
pip install fakeredis pytest pytest-asyncio mypy pylint safety bandit codecov pytest-cov
pytest -v test

Fails at [`test/test_circuit_async.py::test_successful_after_wait` ](https://github.com/arlyon/aiobreaker/blob/master/test/test_circuit_async.py#L142) - when it tried to get the time_remaining
Because of [`CircuitBreakerError::time_remaining`](https://github.com/arlyon/aiobreaker/blob/master/aiobreaker/state.py#L24) - `self.reopen_time` is None and we are performing operand "-" on None and datetime objects

Just wondering what would be the proper dev env setup. Thanks!

**Comment by arlyon** [comment]
Hey @jeffmadrid the answer is this lib needs a bit of cleanup. I was working on it originally for a project that has ended and I don't spend much time on python any more. I can attest that the tests _were_ passing (https://github.com/arlyon/aiobreaker/runs/49802669), but clearly that is no longer the case.

If you have a use for this can would like to be added as a maintainer let me know.

**Comment by jeffmadrid** [comment]
Yeah its possible that this might have been a difference on the OS/interpreter how the time was interpreted or something unpredictable, not exactly sure. The main functionality as a circuit breaker still works unaffected by it which is fine.

Sure, it'll be nice to be a maintainer of this Python repo!

Agree, having to support both sync and async can get a little bumpy.

**Comment by arlyon** [comment]
Cool, feel free to fix it up and get a PR and we'll sort out maintainer status then. Thanks for the interest!

**Comment by jeffmadrid** [comment]
Sure. For a start, I was thinking of adding support for the async listeners which there's already a issue on. 

No worries. Thanks for creating this!
